### ISSUE TITLE
Installing without cert-manager or secret permissions

### ISSUE THREAD

**Issue by teksuo** [k8tz/k8tz#109]
Hi there, 

I want to install this chart without any cert-manager related config and therefore without providing permissions to **get**,**list** and **watch** secrets.

Is this possible or even in the roadmap?

Thanks in advance

**Comment by yonatankahana** [comment]
Hi @teksuo,

apparently it was a bug, so i fixed it in #110 and you can use 0.17.1 right now.

Thanks for the report!
