### ISSUE TITLE
This project is really nice, I hope to support StatefulSet injection as soon as possible

### ISSUE THREAD

**Issue by 1121437613** [k8tz/k8tz#11]
This project is really nice, I hope to support StatefulSet injection as soon as possible.

**Comment by yonatankahana** [comment]
Hi @1121437613, i am happy to hear!
you can look at how `Deployment` is implemented, the `StatefulSet` should be pretty close to that: https://github.com/k8tz/k8tz/blob/50729bd0e68659a1df91fcf390948bc243d9c7b5/pkg/inject/inject.go#L87-L91
