### ISSUE TITLE
 admission.go:62: --kubeconfig not specified.

### ISSUE THREAD

**Issue by humrobin** [k8tz/k8tz#18]
hello,when i use "  helm install k8tz k8tz/k8tz   -f values.yaml"
but the container logs tell me ,
INFO: 2022/04/19 14:56:16 server.go:67: k8tz v0.4.0 go1.17 linux/amd64
WARNING: 2022/04/19 14:56:16 admission.go:62: --kubeconfig not specified. Using the inClusterConfig. This might not work.
INFO: 2022/04/19 14:56:16 server.go:78: Listening on :8443

could u tell me ,How can I solve this problem

**Comment by yonatankahana** [comment]
Hi @humrobin,
You can ignore it.
The warning warns about that the parameter not specified, therefore it will fallback to in-cluster config and this might fail if you are not running as a pod inside cluster. But its just confusing for 99% of users. I'll hide it and update you when the new version will be available.
Thanks :+1:
