### ISSUE TITLE
 failed to lookup pod's namespace (default/ntp2): Unauthorized

### ISSUE THREAD

**Issue by fanux** [k8tz/k8tz#22]
root@iZj6ce0h880med3ug4nr1mZ:~# kubectl run ntp2 --image=docker.io/geoffh1977/chrony --env ALLOW_CIDR=0.0.0.0/0 -n default
Error from server: admission webhook "admission-controller.k8tz.io" denied the request: failed to lookup generator, error: failed to lookup pod's namespace (default/ntp2): Unauthorized

**Comment by yonatankahana** [comment]
Hi @fanux,
i'll need some more information
1. what kubernetes version you are using? can you show `kubectl version` information?
2. how k8tz installed? can you provide the `helm install` command?
3. there are some steps that can reproduce the problem (prior to `kubectl run`)?

**Comment by fanux** [comment]
1. we use kubernetes v1.24.0
2. yes, useing helm install command
3. seems I can't reproduce it now... I don't know why..
