### ISSUE TITLE
It would be better if it could support inject timezones into pods only namespaces with labels

### ISSUE THREAD

**Issue by 1121437613** [k8tz/k8tz#28]
For the most part, k8tz works great, but I get confused when I want pods under certain namespaces not to be timezone injected.
Hope to support inject the timezone into the pod only if the namespace has a label.

**Comment by yonatankahana** [comment]
Hi @1121437613,
you can disable injection by default (`--set injectAll=false`) and then it will inject only to namespaces that have an explicit `k8tz.io/inject: true` annotation

```
helm upgrade --install k8tz k8tz/k8tz --set injectAll=false
kubectl annotate --overwrite namespace my-specific-namespace k8tz.io/inject=true
```

**Comment by 1121437613** [comment]
> Hi @1121437613, k8tz injection is enabled by default, but you can add annotation to namespaces that you don't want to inject by default
> 
> ```
> kubectl annotate --overwrite namespace my-specific-namespace k8tz.io/inject=false
> ```
> 
> you can also disable injection by default (`--set injectAll=false`) and then it will inject only to namespaces that have an explicit `k8tz.io/inject: true` annotation
> 
> ```
> helm upgrade --install k8tz k8tz/k8tz --set injectAll=false
> kubectl annotate --overwrite namespace my-specific-namespace k8tz.io/inject=true
> ```
> 
> you can also annotate a specific deployment
> 
> ```
> kubectl annotate --overwrite deployment my-specific-deployment k8tz.io/inject=true k8tz.io/timezone=Canada/Pacific
> ```
> 
> annotation on deployment is prior to annotation on namespace, and namespace annotations are prior to values provided to helm (--set) you can play with those levels of configurations to achieve the best setup for you

Thank you for your reply, it solved my problem.

**Comment by nothinggift** [comment]
> kubectl annotate --overwrite deployment my-specific-deployment k8tz.io/inject=false

I tried to prevent injection with annotations k8tz.io/inject=true and k8tz.io/timezone=UTC but nothing works
k8s version 1.24.3
k8tz version 0.7.0

I tried copying the deployment to a different namespace, but it didn't work

**Comment by nothinggift** [comment]
my bad, it was a copy error
`k8tz.io/inject=false`  does nothing

**Comment by nothinggift** [comment]
Thanks！it worked！
