### ISSUE TITLE
pod securityContext: runAsNonRoot

### ISSUE THREAD

**Issue by chenhuazhong** [k8tz/k8tz#35]
Events:
  Type     Reason     Age                             From               Message
  ----     ------     ----                            ----               -------
  Normal   Scheduled  26m                             default-scheduler  Successfully assigned default/test-k8tz to node2
  Warning  Failed     <invalid> (x12 over <invalid>)  kubelet            Error: container has runAsNonRoot and image has non-numeric user (k8tz), cannot verify user is non-root (pod: "test-k8tz_default(4308d622-b565-4067-a243-15bb7897a89f)", container: k8tz)
  Normal   Pulled     <invalid> (x94 over <invalid>)  kubelet            Container image "quay.io/k8tz/k8tz:0.5.0test" already present on machine

pod status 
root@master ~]# kubectl get pod 
NAME        READY   STATUS                            RESTARTS   AGE
centos      1/1     Terminating                       0          4h33m
test-k8tz   0/1     Init:CreateContainerConfigError   0          26m

pod yaml

`apiVersion: v1
kind: Pod
metadata:
  name: test-k8tz
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - env:
    - name: TZ
      value: Asia/Shanghai
    image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /etc/localtime
      name: data
      readOnly: true
      subPath: Asia/Shanghai
    - mountPath: /usr/share/zoneinfo
      name: data
      readOnly: true
  volumes:
  - hostPath:
      path: /usr/share/zoneinfo
    name: data
`

Sidecar container should be started with non root to avoid conflict with securitycontext

**Comment by yonatankahana** [comment]
Hi @chenhuazhong,
this bug already fixed one version later ([v0.5.1](https://github.com/k8tz/k8tz/releases/tag/v0.5.1)).
try to [upgrade](https://github.com/k8tz/k8tz/tree/master/charts/k8tz#upgrade) and let me know if it solves your problem.

**Comment by chenhuazhong** [comment]
It's OK after upgrading

**Comment by yonatankahana** [comment]
> It's OK after upgrading

excellent!
