### ISSUE TITLE
Installing k8tz in airgap environment

### ISSUE THREAD

**Issue by Vinnyaaa** [k8tz/k8tz#42]
Hi

Being not very versed in use of kubernetes and how to inject timezone manually i tested k8tz in a test env with internet access and it seems to work great.
However are the any way to install k8tz in an airgapped environment?
If yes, how do i accomplish that?

**Comment by yonatankahana** [comment]
Hi @Vinnyaaa,
To install k8tz in an airgapped environment you need to make sure that the image (`quay.io/k8tz/k8tz:0.8.0`) is available in all cluster nodes.
If you are using local container registry (such as nexus or artifactory) you need to push the image to your registry and when installing k8tz, specify custom repository, for example: `helm install k8tz k8tz/k8tz --set image.repository=my-private-registry.domain.local:5000 --set timezone=Europe/London`
