### ISSUE TITLE
Daemonset chart option

### ISSUE THREAD

**Issue by brightdroid** [k8tz/k8tz#43]
It would be nice if you add a values-option to use a Daemonset instead of deployment.

Thank you in advance

**Comment by brightdroid** [comment]
Thank you 👍

**Comment by brightdroid** [comment]
Did you forget to push a new version? Version 0.10.0 doesn't have the new kind value.

Thanks you again

**Comment by yonatankahana** [comment]
hi @brightdroid, the changes have been merged but not yet released. I am planning to release v0.11.0 as soon as #45 will be merged

**Comment by brightdroid** [comment]
Ok, thank you.

**Comment by yonatankahana** [comment]
@brightdroid you can now use this feature in chart version 0.11.0

**Comment by brightdroid** [comment]
Thank you, works as expected :)
