### ISSUE TITLE
Timezone injection based on node annotations

### ISSUE THREAD

**Issue by christian-schlichtherle** [k8tz/k8tz#54]
First, thanks for this very useful tool!

It would be great if the k8tz.io/timezone etc annotations would be read from the node too. In our case we are running daemonsets on IoT nodes. Each of these nodes may be located in another timezone, so we need to have the pods somehow read the k8tz annotations from the node, not the pod or namespace.

**Comment by yonatankahana** [comment]
Hi @christian-schlichtherle,
Unfortunately, it is not possible to implement such a feature in kubernetes. When the admission controller processes the pod, it has no way to predict which node it will run on. Moreover, after the pod is created it can move between nodes. In Kubernetes, pod is immutable resource, which means that it cannot be changed after creation.

What I can recommend instead is to create a Deployment for each timezone with a corresponding node affinity.

Hope it helps :)

**Comment by christian-schlichtherle** [comment]
Thanks for the feedback! Then we are going to continue with what we're already doing, which is reading node annotations at runtime in the container.
