### ISSUE TITLE
inject into running resources

### ISSUE THREAD

**Issue by si458** [k8tz/k8tz#71]
Hi, brilliant software works a treat! even got it working automatically with talos!
(had to change `failurePolicy` to `Ignore` otherwise the cluster wouldnt start up at all)

but anyways... is it possible to inject the timezone into running pods or only when a pod is created?

**Comment by yonatankahana** [comment]
hi @si458,
I don't think it's possible. First of all, Pods are immutable so k8tz cannot make changes to them after they are created. In addition to this, some applications uses the `TZ` environment variable. The environment variable is used at the start of the application and cannot be changed after process starts.
The best time to affect the time zone is during the creation of the Pod as is the case today.

**Comment by si458** [comment]
Thanks @yonatankahana I did think that was the case but I wanted to double check first!
just annoying all the calico pods and metric pods, etc start when you apply-confog to bootstrap the cluster in talos but they all have the wrong timezone, but everything after the k8tz is started (like when a few calico pods restart) have the correct timezone

**Comment by yonatankahana** [comment]
Yes, it's a chicken and egg problem with admission controllers. The best recommendation I can give is to upload as few pods as possible until k8tz is installed and then start installing other things. 
And if possible - delete the pods created before k8tz and create them again (i.e rollout restart).
