### ISSUE TITLE
cronjob have error 

### ISSUE THREAD

**Issue by ufwtlsb** [k8tz/k8tz#72]
2023/07/31 09:07:08 http: panic serving 172.17.0.1:52534: runtime error: invalid
 memory address or nil pointer dereference
goroutine 313321 [running]:
net/http.(*conn).serve.func1()
    /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1825 +0xbf
panic({0x16da100, 0x271d250})
    /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
github.com/k8tz/k8tz/pkg/admission.(*RequestsHandler).handleCronJobAdmissionRequest(0x1b?, 0xc0007311e0)
    /home/runner/work/k8tz/k8tz/pkg/admission/admission.go:320 +0x1ce
github.com/k8tz/k8tz/pkg/admission.(*RequestsHandler).handleAdmissionReview(0xc0003c2370?, 0xc000b8db00)
    /home/runner/work/k8tz/k8tz/pkg/admission/admission.go:154 +0x235
github.com/k8tz/k8tz/pkg/admission.(*RequestsHandler).handleFunc(0x0?, {0x1b60ce0, 0xc0005427e0}, 0x4edd29?)
    /home/runner/work/k8tz/k8tz/pkg/admission/admission.go:110 +0x29e
net/http.HandlerFunc.ServeHTTP(0x7f74c23db3a8?, {0x1b60ce0?, 0xc0005427e0?}, 0xc000901610?)
    /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0003e6407?, {0x1b60ce0, 0xc0005427e0}, 0xc0002c2800)
    /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x1b52d68?}, {0x1b60ce0, 0xc0005427e0}, 0xc0002c2800)
    /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00015a5a0, {0x1b61578, 0xc0003e1110})
    /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
    /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x4db

**Comment by ufwtlsb** [comment]
/home/runner/work/k8tz/k8tz/pkg/admission/admission.go:320 
```go
 generator, err := h.lookupCronJob(req.Namespace, &cronJob)
 // generator is null and report error 
 verboseLogger.Printf("Generating patches for cronJob (%s) using generator: %+v"
, formatObjectDetails(cronJob.ObjectMeta), *generator)
 if err != nil {
  return nil, fmt.Errorf("failed to lookup generator for cronJob, error=%w", err
)
 }

```

**Comment by yonatankahana** [comment]
Hi @ufwtlsb,
1. Can you send me the CronJob YAML that caused the error to reproduce it?
2. Does enable [`verbose`](https://github.com/k8tz/k8tz/blob/3fd886cccd808a70ec6a1ada4028c5888e63c6c1/charts/k8tz/values.yaml#L11) flag show more logs before crash?

**Comment by ufwtlsb** [comment]
because i set injectAll is false, so all cronjob is error 
and  generator==null

**Comment by ufwtlsb** [comment]
@yonatankahana 
can release a patch version if fix it
 thanks

**Comment by yonatankahana** [comment]
@ufwtlsb 
can you test the fix?

`--set image.repository=quay.io/yonatankahana/k8tz,image.tag=0.13.1-beta0`

**Comment by ufwtlsb** [comment]
@yonatankahana  
it's fix,thanks
