### ISSUE TITLE
Error: container's runAsUser breaks non-root policy , container: k8tz)

### ISSUE THREAD

**Issue by urbaman** [k8tz/k8tz#81]
Hi,

I do have this error on a pod, probably due to a Security Context.
The pod is longhorn-driver-deployer from the longhorn storage system.

Is there a way to make it work without hacking Longhorn?

Thank you.

**Comment by bjw-s** [comment]
Thanks for the quick fix @yonatankahana! Is there any chance that you could create a release / Docker tag that contains this fix?
