### ISSUE TITLE
k8tz initContainer does not pick up the compute resources from values.yaml

### ISSUE THREAD

**Issue by feizhe1996** [k8tz/k8tz#83]
When the namespace is guarded by a resource quota, each container needs to specify the resource requirement.
I found that the initContainer launched by the k8tz webhook does not  pick up the compute resources from values.yaml.
It seems that the compute resource only gets applied to the webhook controller pod.

This leads to k8s throwing quota errors:
Error creating: pods "xxxx" is forbidden: failed quota: compute-resources: must specify requests.cpu for: k8tz; requests.memory for: k8tz

**Comment by Sebastian-RG** [comment]
This affects me. Thank you for your PR! Hope it gets merged soon!

**Comment by yonatankahana** [comment]
fixed in #85 and released in v0.16.1.
