### ISSUE TITLE
Unable to deploy helm chart to existing namespace

### ISSUE THREAD

**Issue by tothdavid** [k8tz/k8tz#91]
So I am using terraform to deploy the k8tz helm chart to a cluster. However I seem to have a little chicken and egg problem here, since I am using a private registry to deploy both your chart and docker image so I need an imagePullSecret to be deployed in the same namespace so that pod can start up properly. Without this the helm deployment fails, because it is actually waiting for the controller Deployment to be healthy.  
But since you have a namespace defined in the helm chart it is impossible to deploy it in an existing namespace, so it is impossible to have a secret there at the time of the deployment. So essentially it is impossible to successfully deploy this in a single run with a private registry.  

So my suggestion would be to make namespace creation optional (like it is proposed in PR https://github.com/k8tz/k8tz/pull/86 , but probably I would go with the backward compatible approach, and would not introduce a breaking change.). However I do understand the reason why you have the namespace in the chart, so that you can apply the controller-namespace annotation to it, so k8tz will not try to inject itself. But maybe anyone creating the namespace externally could just make sure that either the namespace is annotated, or we could even add the namespace name to the namespaceSelector of the admission webhook just like the `.Values.webhook.ignoredNamespaces`. Another option would be to make it possible to opt out of the webhook rules on a pod level instead of just namespace level (currently the webhook is called for pod level annotations, and the controller will just ignore those, but for the k8tz pod it would not be enough) and annotate the k8tz pod itself. Probably using the objectSelector could work for that as well.

**Comment by yonatankahana** [comment]
Hi @tothdavid,
Sorry for the delay, the problem is familiar to me, but to date I have not received a PR that fixes the problem in a way that I am satisfied with.
I will try to give backward compatible solution, if you can - please test (and follow) PR #92

**Comment by tothdavid** [comment]
Thanks for fixing this!
